### ISSUE TITLE
Request for Pre-trained Checkpoints

### ISSUE THREAD

**Issue by oopstom** [atomicarchitects/symphony#125]
Dear Authors,

Thank you for sharing your excellent work on SYMPHONY. The paper presents a fascinating approach to 3D molecular generation, and I am excited to explore your method further.

I wanted to inquire if you have any **pre-trained** checkpoints available for download. It would be incredibly helpful for reproducing the results and experimenting with the model without starting from scratch.

If the checkpoints are not yet available, could you kindly provide guidance on how to best proceed with training the model from scratch, including any specific hardware or runtime recommendations?

Thank you for your contributions to this field, and I look forward to your response!

Best regards,
Yuqi

**Comment by ameya98** [comment]
Hi,
Very sorry! I completely missed this. You can find the pre-trained checkpoint here: https://github.com/atomicarchitects/symphony/blob/tutorial/tutorial/workdir/checkpoints/params_best.pkl

We will improve the accessibility of this repository soon.
Let me know if we can help in any other way!
